feat:
  - head-branch: ['^feat']
fix:
  - head-branch: ['^fix']
chore:
  - head-branch: ['^chore']
  - head-branch: ['^refactor']
  - head-branch: ['^style']
  - head-branch: ['^ci']
doc:
  - head-branch: ['^doc']
