env:
  commonjs: true
  es6: true
  node: true
root: true
extends:
  - airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules: {}
settings:
  import/external-module-folders: ["."]
