service: serverless-s3-local-example
provider:
  name: aws
  runtime: nodejs18.x
plugins:
  - serverless-s3-local
  - serverless-offline
custom:
  s3Local:
    minio:
      port: 9000
      fetchFromWeb: false
functions:
  webhook:
    handler: handler.webhook
    events:
      - http:
          path: /
          method: GET
  s3hook:
    handler: handler.s3hook
    environment:
      ENV_000: 123
      ENV_001: 456
    events:
      - s3:
          bucket: local-bucket
          event: s3:ObjectCreated:Put
          existing: true  # existing is ignored