service: serverless-s3-local-example
provider:
  name: aws
  runtime: nodejs18.x
plugins:
  - serverless-s3-local
  - serverless-offline
resources:
  Resources:
    NewResource:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: local-bucket
functions:
  webhook:
    handler: handler.webhook
    events:
      - http:
          path: /
          method: GET
  s3hook:
    handler: handler.s3hook
    environment:
      ENV_000: 123
      ENV_001: 456
    events:
      - s3: local-bucket
