service: serverless-s3-local-example
provider:
  name: aws
  runtime: nodejs18.x
plugins:
  - serverless-webpack
  - serverless-s3-local
  - serverless-offline
custom:
  webpackIncludeModules: true
  minio:
    port: 9000
resources:
  Resources:
    NewResource:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: local-bucket
functions:
  webhook:
    handler: src/handler.webhook
    events:
      - http:
          method: GET
          path: /
  s3hook:
    handler: src/handler.s3hook
    events:
      - s3: local-bucket
