# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  push:
    branches-ignore:
      - 'bump-v*'
    tags-ignore:
      - v*


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: test put-with-s3-event-response
        shell: bash
        run: docker-compose -f ./test/docker-compose.yml run put-with-s3-event-response
      - name: test resize-image
        shell: bash
        run: docker-compose -f ./test/docker-compose.yml run resize-image
      - name: test simple-event
        shell: bash
        run: docker-compose -f ./test/docker-compose.yml run simple-event
      - name: test simple-event-python
        shell: bash
        run: docker-compose -f ./test/docker-compose.yml run simple-event-python
      - name: test simple-put
        shell: bash
        run: docker-compose -f ./test/docker-compose.yml run simple-put
      - name: test webpack-support
        shell: bash
        run: docker-compose -f ./test/docker-compose.yml run webpack-support
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo, commit, message
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: always()
